baseURL = "https://hellebusch.io"
languageCode = "en-us"
title = "hellebusch.io"
theme = "hugo-coder"
enableEmoji = true

[params] # theme parameters
    author = "Sean Hellebusch"
    info = "Software engineer, outdoor enthusiast."
    description = "Ramblings of a developer who enjoys his work."
    keywords = "blog,developer,personal"
    
# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/sahellebusch/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/sahellebusch/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"